vim.api.nvim_set_hl(0, "WinSeparator", { guibg=None })
vim.api.nvim_set_hl(0, "Normal", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "NonText", { ctermbg=NONE, ctermfg=0 })
vim.api.nvim_set_hl(0, "Comment", { ctermbg=NONE, ctermfg=8 })
vim.api.nvim_set_hl(0, "Conceal", { ctermbg=NONE })
vim.api.nvim_set_hl(0, "Constant", { ctermbg=NONE, ctermfg=3 })
vim.api.nvim_set_hl(0, "Error", { ctermbg=1, ctermfg=7 })
vim.api.nvim_set_hl(0, "Identifier", { ctermbg=NONE, ctermfg=1, cterm=BOLD })
vim.api.nvim_set_hl(0, "Ignore", { ctermbg=8, ctermfg=0 })
vim.api.nvim_set_hl(0, "PreProc", { ctermbg=NONE, ctermfg=3 })
vim.api.nvim_set_hl(0, "Special", { ctermbg=NONE, ctermfg=6 })
vim.api.nvim_set_hl(0, "Statement", { ctermbg=NONE, ctermfg=1 })
vim.api.nvim_set_hl(0, "String", { ctermbg=NONE, ctermfg=2 })
vim.api.nvim_set_hl(0, "Number", { ctermbg=NONE, ctermfg=3 })
vim.api.nvim_set_hl(0, "Todo", { ctermbg=2, ctermfg=0 })
vim.api.nvim_set_hl(0, "Type", { ctermbg=NONE, ctermfg=3 })
vim.api.nvim_set_hl(0, "Underlined", { ctermbg=NONE, ctermfg=1, cterm=underline })
vim.api.nvim_set_hl(0, "StatusLine", { ctermbg=7, ctermfg=0 })
vim.api.nvim_set_hl(0, "StatusLineNC", { ctermbg=8, ctermfg=0 })
vim.api.nvim_set_hl(0, "TabLine", { ctermbg=NONE, ctermfg=8 })
vim.api.nvim_set_hl(0, "TabLineFill", { ctermbg=NONE, ctermfg=8 })
vim.api.nvim_set_hl(0, "TabLineSel", { ctermbg=4, ctermfg=0 })
vim.api.nvim_set_hl(0, "TermCursorNC", { ctermbg=3, ctermfg=0 })
vim.api.nvim_set_hl(0, "VertSplit", { ctermbg=8, ctermfg=0 })
vim.api.nvim_set_hl(0, "Title", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "CursorLine", { ctermbg=2, ctermfg=0 })
vim.api.nvim_set_hl(0, "LineNr", { ctermbg=NONE, ctermfg=8 })
vim.api.nvim_set_hl(0, "CursorLineNr", { ctermbg=NONE, ctermfg=8 })
vim.api.nvim_set_hl(0, "helpLeadBlank", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "helpNormal", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "Visual", { ctermbg=1, ctermfg=15, cterm=reverse, term=reverse })
vim.api.nvim_set_hl(0, "VisualNOS", { ctermbg=NONE, ctermfg=1 })
vim.api.nvim_set_hl(0, "Pmenu", { ctermbg=8, ctermfg=7 })
vim.api.nvim_set_hl(0, "PmenuSbar", { ctermbg=6, ctermfg=7 })
vim.api.nvim_set_hl(0, "PmenuSel", { ctermbg=4, ctermfg=0 })
vim.api.nvim_set_hl(0, "PmenuThumb", { ctermbg=8, ctermfg=8 })
vim.api.nvim_set_hl(0, "FoldColumn", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "Folded", { ctermbg=NONE, ctermfg=8 })
vim.api.nvim_set_hl(0, "WildMenu", { ctermbg=2, ctermfg=0 })
vim.api.nvim_set_hl(0, "SpecialKey", { ctermbg=NONE, ctermfg=8 })
vim.api.nvim_set_hl(0, "DiffAdd", { ctermbg=NONE, ctermfg=2 })
vim.api.nvim_set_hl(0, "DiffChange", { ctermbg=NONE, ctermfg=8 })
vim.api.nvim_set_hl(0, "DiffDelete", { ctermbg=NONE, ctermfg=1 })
vim.api.nvim_set_hl(0, "DiffText", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "IncSearch", { ctermbg=3, ctermfg=0 })
vim.api.nvim_set_hl(0, "Search", { ctermbg=3, ctermfg=0 })
vim.api.nvim_set_hl(0, "Directory", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "MatchParen", { ctermbg=1, ctermfg=8 })
vim.api.nvim_set_hl(0, "ColorColumn", { ctermbg=4, ctermfg=0 })
vim.api.nvim_set_hl(0, "signColumn", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "ErrorMsg", { ctermbg=NONE, ctermfg=8 })
vim.api.nvim_set_hl(0, "ModeMsg", { ctermbg=NONE, ctermfg=2 })
vim.api.nvim_set_hl(0, "MoreMsg", { ctermbg=NONE, ctermfg=2 })
vim.api.nvim_set_hl(0, "Question", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "WarningMsg", { ctermbg=1, ctermfg=0 })
vim.api.nvim_set_hl(0, "Cursor", { ctermbg=NONE, ctermfg=8 })
vim.api.nvim_set_hl(0, "Structure", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "CursorColumn", { ctermbg=8, ctermfg=7 })
vim.api.nvim_set_hl(0, "ModeMsg", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "SpellBad", { ctermbg=NONE, ctermfg=1, cterm=underline })
vim.api.nvim_set_hl(0, "SpellCap", { ctermbg=NONE, ctermfg=4, cterm=underline })
vim.api.nvim_set_hl(0, "SpellLocal", { ctermbg=NONE, ctermfg=5, cterm=underline })
vim.api.nvim_set_hl(0, "SpellRare", { ctermbg=NONE, ctermfg=6, cterm=underline })
vim.api.nvim_set_hl(0, "Boolean", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "Character", { ctermbg=NONE, ctermfg=1 })
vim.api.nvim_set_hl(0, "Conditional", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "Define", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "Delimiter", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "Float", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "Include", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "Keyword", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "Label", { ctermbg=NONE, ctermfg=3 })
vim.api.nvim_set_hl(0, "Operator", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "Repeat", { ctermbg=NONE, ctermfg=3 })
vim.api.nvim_set_hl(0, "SpecialChar", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "Tag", { ctermbg=NONE, ctermfg=3 })
vim.api.nvim_set_hl(0, "Typedef", { ctermbg=NONE, ctermfg=3 })
vim.api.nvim_set_hl(0, "vimUserCommand", { ctermbg=NONE, ctermfg=1, cterm=BOLD })
vim.api.nvim_set_hl(0, "link", { vimMap, vimUserCommand })
vim.api.nvim_set_hl(0, "link", { vimLet, vimUserCommand })
vim.api.nvim_set_hl(0, "link", { vimCommand, vimUserCommand })
vim.api.nvim_set_hl(0, "link", { vimFTCmd, vimUserCommand })
vim.api.nvim_set_hl(0, "link", { vimAutoCmd, vimUserCommand })
vim.api.nvim_set_hl(0, "link", { vimNotFunc, vimUserCommand })
vim.api.nvim_set_hl(0, "vimNotation", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "vimMapModKey", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "vimBracket", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "vimCommentString", { ctermbg=NONE, ctermfg=8 })
vim.api.nvim_set_hl(0, "htmlLink", { ctermbg=NONE, ctermfg=1, cterm=underline })
vim.api.nvim_set_hl(0, "htmlBold", { ctermbg=NONE, ctermfg=3, cterm=BOLD })
vim.api.nvim_set_hl(0, "htmlItalic", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "htmlEndTag", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "htmlTag", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "htmlTagName", { ctermbg=NONE, ctermfg=1, cterm=BOLD })
vim.api.nvim_set_hl(0, "htmlH1", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "link", { htmlH2, htmlH1 })
vim.api.nvim_set_hl(0, "link", { htmlH3, htmlH1 })
vim.api.nvim_set_hl(0, "link", { htmlH4, htmlH1 })
vim.api.nvim_set_hl(0, "link", { htmlH5, htmlH1 })
vim.api.nvim_set_hl(0, "link", { htmlH6, htmlH1 })
vim.api.nvim_set_hl(0, "cssMultiColumnAttr", { ctermbg=NONE, ctermfg=2 })
vim.api.nvim_set_hl(0, "link", { cssFontAttr, cssMultiColumnAttr })
vim.api.nvim_set_hl(0, "link", { cssFlexibleBoxAttr, cssMultiColumnAttr })
vim.api.nvim_set_hl(0, "cssBraces", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "link", { cssAttrComma, cssBraces })
vim.api.nvim_set_hl(0, "cssValueLength", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "cssUnitDecorators", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "cssValueNumber", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "link", { cssValueLength, cssValueNumber })
vim.api.nvim_set_hl(0, "cssNoise", { ctermbg=NONE, ctermfg=8 })
vim.api.nvim_set_hl(0, "cssTagName", { ctermbg=NONE, ctermfg=1 })
vim.api.nvim_set_hl(0, "cssFunctionName", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "scssSelectorChar", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "scssAttribute", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "link", { scssDefinition, cssNoise })
vim.api.nvim_set_hl(0, "sassidChar", { ctermbg=NONE, ctermfg=1 })
vim.api.nvim_set_hl(0, "sassClassChar", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "sassInclude", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "sassMixing", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "sassMixinName", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "javaScript", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "javaScriptBraces", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "javaScriptNumber", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "markdownH1", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "link", { markdownH2, markdownH1 })
vim.api.nvim_set_hl(0, "link", { markdownH3, markdownH1 })
vim.api.nvim_set_hl(0, "link", { markdownH4, markdownH1 })
vim.api.nvim_set_hl(0, "link", { markdownH5, markdownH1 })
vim.api.nvim_set_hl(0, "link", { markdownH6, markdownH1 })
vim.api.nvim_set_hl(0, "markdownAutomaticLink", { ctermbg=NONE, ctermfg=2, cterm=underline })
vim.api.nvim_set_hl(0, "link", { markdownUrl, markdownAutomaticLink })
vim.api.nvim_set_hl(0, "markdownError", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "markdownCode", { ctermbg=NONE, ctermfg=3 })
vim.api.nvim_set_hl(0, "markdownCodeBlock", { ctermbg=NONE, ctermfg=3 })
vim.api.nvim_set_hl(0, "markdownCodeDelimiter", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "markdownItalic", { cterm=Italic })
vim.api.nvim_set_hl(0, "markdownBold", { cterm=Bold })
vim.api.nvim_set_hl(0, "xdefaultsValue", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "rubyInclude", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "rubyDefine", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "rubyFunction", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "rubyStringDelimiter", { ctermbg=NONE, ctermfg=2 })
vim.api.nvim_set_hl(0, "rubyInteger", { ctermbg=NONE, ctermfg=3 })
vim.api.nvim_set_hl(0, "rubyAttribute", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "rubyConstant", { ctermbg=NONE, ctermfg=3 })
vim.api.nvim_set_hl(0, "rubyInterpolation", { ctermbg=NONE, ctermfg=2 })
vim.api.nvim_set_hl(0, "rubyInterpolationDelimiter", { ctermbg=NONE, ctermfg=3 })
vim.api.nvim_set_hl(0, "rubyRegexp", { ctermbg=NONE, ctermfg=6 })
vim.api.nvim_set_hl(0, "rubySymbol", { ctermbg=NONE, ctermfg=2 })
vim.api.nvim_set_hl(0, "rubyTodo", { ctermbg=NONE, ctermfg=8 })
vim.api.nvim_set_hl(0, "rubyRegexpAnchor", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "link", { rubyRegexpQuantifier, rubyRegexpAnchor })
vim.api.nvim_set_hl(0, "pythonOperator", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "pythonFunction", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "pythonRepeat", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "pythonStatement", { ctermbg=NONE, ctermfg=1, cterm=Bold })
vim.api.nvim_set_hl(0, "pythonBuiltIn", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "phpMemberSelector", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "phpComparison", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "phpParent", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "cOperator", { ctermbg=NONE, ctermfg=6 })
vim.api.nvim_set_hl(0, "cPreCondit", { ctermbg=NONE, ctermfg=5 })
vim.api.nvim_set_hl(0, "SignifySignAdd", { ctermbg=NONE, ctermfg=2 })
vim.api.nvim_set_hl(0, "SignifySignChange", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "SignifySignDelete", { ctermbg=NONE, ctermfg=1 })
vim.api.nvim_set_hl(0, "NERDTreeDirSlash", { ctermbg=NONE, ctermfg=4 })
vim.api.nvim_set_hl(0, "NERDTreeExecFile", { ctermbg=NONE, ctermfg=7 })
vim.api.nvim_set_hl(0, "ALEErrorSign", { ctermbg=NONE, ctermfg=1 })
vim.api.nvim_set_hl(0, "ALEWarningSign", { ctermbg=NONE, ctermfg=3 })
vim.api.nvim_set_hl(0, "ALEError", { ctermbg=NONE, ctermfg=1 })
vim.api.nvim_set_hl(0, "ALEWarning", { ctermbg=NONE, ctermfg=3 })
