#!/bin/sh

xrandr --dpi 96
fehbg &
pipewire &
calcurse --daemon &
xrdb ~/.config/x11/xresources & xrdbpid=$!

autostart="remap mpd dunst fcitx5 pipewire-pulse syncthing"

for program in $autostart; do
  pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

[ -n "$xrdbpid" ] && wait "$xrdbpid"
