#!/bin/sh

dwmblocks &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!
fehbg &

xset r rate 300 50 &
setxkbmap -option caps:escape &
xset -q | grep "Caps Lock:\s*on" && xdotool key Caps_Lock &

pipewire &
pipewire-pulse &

dunst &
fcitx5 &
syncthing &
ollama serve &

mpd &
mpdup &
calcurse --daemon &

[ -n "$xrdbpid" ] && wait "$xrdbpid"
