#!/bin/sh

xrandr --dpi 96
fehbg &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!

pipewire &
calcurse --daemon &
remap &
mpd &
mpdup &
dunst &
fcitx5 &
pipewire-pulse &
syncthing &
ollama serve &

[ -n "$xrdbpid" ] && wait "$xrdbpid"
